services:
  postgres:
    ports:
      - "127.0.0.1:[host_port]:[container_port]"
    restart: unless-stopped

  backend:
    ports:
      - "127.0.0.1:[host_port]:[container_port]"
    restart: unless-stopped
