services:
  postgres:
    container_name: webDAV_db
    image: postgres:17-alpine
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    container_name: webDAV_redis
    image: redis:latest
    volumes:
      - ./backend/cache/redis.conf:/usr/local/etc/redis/redis.conf
      - redis-data:/data
      - ./backend/logs/redis-logs:/redis-logs
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass ${REDIS_PASSWORD}

  backend:
    container_name: webDAV_backend
    build:
      context: ./backend
    env_file:
      - .env
    volumes:
      - ./backend:/app
    depends_on:
      - postgres

  frontend:
    container_name: webDAV_frontend
    build:
      context: ./frontend
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    depends_on:
      - backend

volumes:
  pgdata:
  redis-data:
