version: "2"

linters:
  enable:
    - bodyclose
    - errorlint
    - gocritic
    - misspell
    - revive
    - unconvert
    - unparam

  settings:
    revive:
      rules:
        - name: exported
          disabled: true
        - name: package-comments
          disabled: true

formatters:
  enable:
    - gofmt
    - goimports

