// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: files.sql

package sqlc

import (
	"context"
)

const deleteFile = `-- name: DeleteFile :one
delete from files where id = $1 and user_id = $2
returning filename
`

type DeleteFileParams struct {
	ID     int32
	UserID int32
}

func (q *Queries) DeleteFile(ctx context.Context, arg DeleteFileParams) (string, error) {
	row := q.db.QueryRow(ctx, deleteFile, arg.ID, arg.UserID)
	var filename string
	err := row.Scan(&filename)
	return filename, err
}

const getAllUserFiles = `-- name: GetAllUserFiles :many
select filename from files where user_id = $1
`

func (q *Queries) GetAllUserFiles(ctx context.Context, userID int32) ([]string, error) {
	rows, err := q.db.Query(ctx, getAllUserFiles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var filename string
		if err := rows.Scan(&filename); err != nil {
			return nil, err
		}
		items = append(items, filename)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFileName = `-- name: GetFileName :one
select filename from files where id = $1
`

func (q *Queries) GetFileName(ctx context.Context, id int32) (string, error) {
	row := q.db.QueryRow(ctx, getFileName, id)
	var filename string
	err := row.Scan(&filename)
	return filename, err
}
