// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: files.sql

package sqlc

import (
	"context"
)

const getAllUserFiles = `-- name: GetAllUserFiles :many
select filename from files where user_id = $1
`

func (q *Queries) GetAllUserFiles(ctx context.Context, userID int32) ([]string, error) {
	rows, err := q.db.Query(ctx, getAllUserFiles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var filename string
		if err := rows.Scan(&filename); err != nil {
			return nil, err
		}
		items = append(items, filename)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
