// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type File struct {
	ID        int32
	UserID    int32
	Filename  string
	FileType  string
	DiskPath  string
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID           int32
	Email        string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
	Active       bool
}
