// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type File struct {
	ID        int32              `json:"id"`
	UserID    int32              `json:"user_id"`
	Filename  string             `json:"filename"`
	FileType  string             `json:"file_type"`
	DiskPath  string             `json:"disk_path"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           int32              `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	Active       bool               `json:"active"`
}
