// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package sqlc

import (
	"context"
)

const activateUser = `-- name: ActivateUser :exec
update users set active = true where id = $1
`

func (q *Queries) ActivateUser(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, activateUser, id)
	return err
}

const changeUserEmail = `-- name: ChangeUserEmail :exec
update users set email = $1 where id = $2
`

type ChangeUserEmailParams struct {
	Email string `json:"email"`
	ID    int32  `json:"id"`
}

func (q *Queries) ChangeUserEmail(ctx context.Context, arg ChangeUserEmailParams) error {
	_, err := q.db.Exec(ctx, changeUserEmail, arg.Email, arg.ID)
	return err
}

const changeUserPassword = `-- name: ChangeUserPassword :exec
update users set password_hash = $1 where id = $2
`

type ChangeUserPasswordParams struct {
	PasswordHash string `json:"password_hash"`
	ID           int32  `json:"id"`
}

func (q *Queries) ChangeUserPassword(ctx context.Context, arg ChangeUserPasswordParams) error {
	_, err := q.db.Exec(ctx, changeUserPassword, arg.PasswordHash, arg.ID)
	return err
}

const createUser = `-- name: CreateUser :one
insert into users (email, password_hash)
  values ($1, $2)
  returning id
`

type CreateUserParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (int32, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const deactivateUser = `-- name: DeactivateUser :exec
update users set active = false where id = $1
`

func (q *Queries) DeactivateUser(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deactivateUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
select id, email, password_hash, created_at, active from users where email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.Active,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
select id, email, password_hash, created_at, active from users where id = $1
`

func (q *Queries) GetUserById(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.Active,
	)
	return i, err
}
